### ISSUE TITLE
Todo APP 요구사항 명세서

### ISSUE THREAD

**Issue by sywoo0109** [sywoo0109/apply-fe-framwork-at-todo-app#1]
### 만들고자 하는 기능
CRUD 구현

### 작업 목록
1. [ ] 새로운 Todo 항목을 기존 항목에 추가할 수 있는 기능
2. [ ] 현재 Todo 항목을 화면에 보여주는 기능
3. [ ] 항목에 접근해서 내용을 수정, 갱신할 수 있는 기능
4. [ ] 항목을 제거하는 기능

#### 예상 작업 시간
10h
